name: shapeandshare.command.runner
channels:
  - defaults
  - conda-forge
  - joshburt
dependencies:
  - black
  - black-jupyter
  - conda-build
  - coverage
  - isort
  - pip
  - pydantic
  - pylint
  - python=3.10.8
  - python-dotenv
  - setuptools
  - anaconda-client
