apiVersion: v2
name: darkness
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: postgresql
    version: 15.5.18
    repository: https://charts.bitnami.com/bitnami
